### ISSUE TITLE
Treatment of trailing slashes currently is impractical

### ISSUE THREAD

**Issue by nleanba** [linked-solutions/slds#3]
TLDS should treat URLs with and without a trailing slash as synonyms, and when requesting a resource, one should get content in both versions of the URL.

**Comment by retog** [comment]
Moved the issue from TLDS to SLDS as it seems unrelated to templating.

**Comment by retog** [comment]
I have some concerns with this proposal:

- The authomatic redirect would let the resources appear as the same, however as soon a triple is added with a different "slashing" of the resource it splits in two
- The only usecase I see is to allow for sloppy linking, but it does so at the expense of potentially creating confusion on the semantics of the data
- 404 take longer 

What would you think about allowing for explicit redirects instead so that one could manually create redirects for typically misspellled resources?

**Comment by nleanba** [comment]
I just think that https://factsmission.com/faq and https://factsmission.com/faq/ shold give you the same result, the same way https://factsmission.com and https://factsmission.com/ both result in the same page.

**Comment by retog** [comment]
Your comparison doesn't hold, as in one case the / is part of the path section while in the other it separates the host from the non-existent path section in which case the slash is explicitly optional according to the specs.

**Comment by retog** [comment]
Closing in favour of https://github.com/linked-solutions/slds/issues/6
